### ISSUE TITLE
Remove hard coded geometry file names from inside TEveEventDisplay

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Offline#703] opened 2022-02-09 16:59 UTC
There are 3 places inside TEveEventDisplay that open a hard coded geometry file to extract some information.  See below for links to the lines.  There are many problems with this code

1. If a user changes the geometry file in the configuration of GeometryService, they need to remember to edit this file and rebuild the code; if they don't do so, the geometry may be inconsistent.
2. Even if it were a good idea to do this,  the code does not use the ConfigFileLookupPolicy
3. The path names do not begin with Offline/ so they are not compliant with muse setup -1, which is now required.
4. Why is this code inline?
5. It's slow to needlessly read in the geometry file many times.
6. What's with the magic numbers 100 and 600 in GetCaloCenter.
  
I was trying to test other changes and my code crashed because the paths do not begin with Offline/ and I always use muse setup -1.  

The right answer is that if the GeometryService does not provide information that you need, ask for it to be provided.  Please contact the geometry experts for the tracker and calorimeter and ask them to provide this information - it may already exist.

The lines in question are:

https://github.com/Mu2e/Offline/blob/9809901382fc229c25c299f4e3c9904bc5dbbdc6/TEveEventDisplay/src/dict_classes/GeomUtils.h#L20

https://github.com/Mu2e/Offline/blob/9809901382fc229c25c299f4e3c9904bc5dbbdc6/TEveEventDisplay/src/dict_classes/GeomUtils.h#L29

https://github.com/Mu2e/Offline/blob/9809901382fc229c25c299f4e3c9904bc5dbbdc6/TEveEventDisplay/src/dict_classes/GeomUtils.h#L34

**Comment by sophiemiddleton** [comment] 2022-02-09 17:06
Thanks Rob for reminding me about this, I will get on to it ASAP

**Comment by sophiemiddleton** [comment] 2022-02-09 18:36
For the magic numbers I need to figure out how to get the z positons of the clusters, the issue is that they are by defult all z = 0 so we need to translater. X and Y are easy (same as tracker)....Z requires some thought....I could extract the crystal position instead ... let me think

**Comment by sophiemiddleton** [comment] 2022-02-10 17:34
Resolved in https://github.com/Mu2e/Offline/pull/699

**Closed** 2022-08-25 13:31 UTC
Labels: bug, High
